version: '3.7'
services:
    redis:
      extra_hosts:
        - 127.0.0.1
      image: redis:danggeun-bunny
      command: redis-server --port 6379
      container_name: redis_boot
      hostname: redis_boot
      labels:
      - "name=redis"
      - "mode=standalone"
      ports:
             - 6379:6379